version: '3'
services:
  app:
    image: sveotac/mdsaas:v1.0
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:mojstrale02@postgres:5432/postgres
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mojstrale02
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"